# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: train_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13train_service.proto\x12\rtrain_service\"Y\n\x15PurchaseTicketRequest\x12\x11\n\tdeparture\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12!\n\x04user\x18\x03 \x01(\x0b\x32\x13.train_service.User\",\n\x16PurchaseTicketResponse\x12\x12\n\nreceipt_id\x18\x01 \x01(\t\"\'\n\x11GetReceiptRequest\x12\x12\n\nreceipt_id\x18\x01 \x01(\t\"x\n\x12GetReceiptResponse\x12\x11\n\tdeparture\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12!\n\x04user\x18\x03 \x01(\x0b\x32\x13.train_service.User\x12\x12\n\nprice_paid\x18\x04 \x01(\x02\x12\x0c\n\x04seat\x18\x05 \x01(\t\",\n\x19ViewUsersBySectionRequest\x12\x0f\n\x07section\x18\x01 \x01(\t\"@\n\x1aViewUsersBySectionResponse\x12\"\n\x05users\x18\x01 \x03(\x0b\x32\x13.train_service.User\"\'\n\x11RemoveUserRequest\x12\x12\n\nreceipt_id\x18\x01 \x01(\t\"\x14\n\x12RemoveUserResponse\"=\n\x15ModifyUserSeatRequest\x12\x12\n\nreceipt_id\x18\x01 \x01(\t\x12\x10\n\x08new_seat\x18\x02 \x01(\t\"\x18\n\x16ModifyUserSeatResponse\"<\n\x04User\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t2\xe7\x03\n\x0cTrainService\x12_\n\x0ePurchaseTicket\x12$.train_service.PurchaseTicketRequest\x1a%.train_service.PurchaseTicketResponse\"\x00\x12S\n\nGetReceipt\x12 .train_service.GetReceiptRequest\x1a!.train_service.GetReceiptResponse\"\x00\x12k\n\x12ViewUsersBySection\x12(.train_service.ViewUsersBySectionRequest\x1a).train_service.ViewUsersBySectionResponse\"\x00\x12S\n\nRemoveUser\x12 .train_service.RemoveUserRequest\x1a!.train_service.RemoveUserResponse\"\x00\x12_\n\x0eModifyUserSeat\x12$.train_service.ModifyUserSeatRequest\x1a%.train_service.ModifyUserSeatResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'train_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PURCHASETICKETREQUEST']._serialized_start=38
  _globals['_PURCHASETICKETREQUEST']._serialized_end=127
  _globals['_PURCHASETICKETRESPONSE']._serialized_start=129
  _globals['_PURCHASETICKETRESPONSE']._serialized_end=173
  _globals['_GETRECEIPTREQUEST']._serialized_start=175
  _globals['_GETRECEIPTREQUEST']._serialized_end=214
  _globals['_GETRECEIPTRESPONSE']._serialized_start=216
  _globals['_GETRECEIPTRESPONSE']._serialized_end=336
  _globals['_VIEWUSERSBYSECTIONREQUEST']._serialized_start=338
  _globals['_VIEWUSERSBYSECTIONREQUEST']._serialized_end=382
  _globals['_VIEWUSERSBYSECTIONRESPONSE']._serialized_start=384
  _globals['_VIEWUSERSBYSECTIONRESPONSE']._serialized_end=448
  _globals['_REMOVEUSERREQUEST']._serialized_start=450
  _globals['_REMOVEUSERREQUEST']._serialized_end=489
  _globals['_REMOVEUSERRESPONSE']._serialized_start=491
  _globals['_REMOVEUSERRESPONSE']._serialized_end=511
  _globals['_MODIFYUSERSEATREQUEST']._serialized_start=513
  _globals['_MODIFYUSERSEATREQUEST']._serialized_end=574
  _globals['_MODIFYUSERSEATRESPONSE']._serialized_start=576
  _globals['_MODIFYUSERSEATRESPONSE']._serialized_end=600
  _globals['_USER']._serialized_start=602
  _globals['_USER']._serialized_end=662
  _globals['_TRAINSERVICE']._serialized_start=665
  _globals['_TRAINSERVICE']._serialized_end=1152
# @@protoc_insertion_point(module_scope)
