# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import train_service_pb2 as train__service__pb2


class TrainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PurchaseTicket = channel.unary_unary(
                '/train_service.TrainService/PurchaseTicket',
                request_serializer=train__service__pb2.PurchaseTicketRequest.SerializeToString,
                response_deserializer=train__service__pb2.PurchaseTicketResponse.FromString,
                )
        self.GetReceipt = channel.unary_unary(
                '/train_service.TrainService/GetReceipt',
                request_serializer=train__service__pb2.GetReceiptRequest.SerializeToString,
                response_deserializer=train__service__pb2.GetReceiptResponse.FromString,
                )
        self.ViewUsersBySection = channel.unary_unary(
                '/train_service.TrainService/ViewUsersBySection',
                request_serializer=train__service__pb2.ViewUsersBySectionRequest.SerializeToString,
                response_deserializer=train__service__pb2.ViewUsersBySectionResponse.FromString,
                )
        self.RemoveUser = channel.unary_unary(
                '/train_service.TrainService/RemoveUser',
                request_serializer=train__service__pb2.RemoveUserRequest.SerializeToString,
                response_deserializer=train__service__pb2.RemoveUserResponse.FromString,
                )
        self.ModifyUserSeat = channel.unary_unary(
                '/train_service.TrainService/ModifyUserSeat',
                request_serializer=train__service__pb2.ModifyUserSeatRequest.SerializeToString,
                response_deserializer=train__service__pb2.ModifyUserSeatResponse.FromString,
                )


class TrainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PurchaseTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewUsersBySection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyUserSeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PurchaseTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.PurchaseTicket,
                    request_deserializer=train__service__pb2.PurchaseTicketRequest.FromString,
                    response_serializer=train__service__pb2.PurchaseTicketResponse.SerializeToString,
            ),
            'GetReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceipt,
                    request_deserializer=train__service__pb2.GetReceiptRequest.FromString,
                    response_serializer=train__service__pb2.GetReceiptResponse.SerializeToString,
            ),
            'ViewUsersBySection': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewUsersBySection,
                    request_deserializer=train__service__pb2.ViewUsersBySectionRequest.FromString,
                    response_serializer=train__service__pb2.ViewUsersBySectionResponse.SerializeToString,
            ),
            'RemoveUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUser,
                    request_deserializer=train__service__pb2.RemoveUserRequest.FromString,
                    response_serializer=train__service__pb2.RemoveUserResponse.SerializeToString,
            ),
            'ModifyUserSeat': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyUserSeat,
                    request_deserializer=train__service__pb2.ModifyUserSeatRequest.FromString,
                    response_serializer=train__service__pb2.ModifyUserSeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'train_service.TrainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PurchaseTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/train_service.TrainService/PurchaseTicket',
            train__service__pb2.PurchaseTicketRequest.SerializeToString,
            train__service__pb2.PurchaseTicketResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/train_service.TrainService/GetReceipt',
            train__service__pb2.GetReceiptRequest.SerializeToString,
            train__service__pb2.GetReceiptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ViewUsersBySection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/train_service.TrainService/ViewUsersBySection',
            train__service__pb2.ViewUsersBySectionRequest.SerializeToString,
            train__service__pb2.ViewUsersBySectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/train_service.TrainService/RemoveUser',
            train__service__pb2.RemoveUserRequest.SerializeToString,
            train__service__pb2.RemoveUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModifyUserSeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/train_service.TrainService/ModifyUserSeat',
            train__service__pb2.ModifyUserSeatRequest.SerializeToString,
            train__service__pb2.ModifyUserSeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
